""" file: __init__.py (pydym)
    author: Jess Robertsonm
            CSIRO Minerals Resources Flagship
    date:   Tuesday 24 June, 2014

    description: Imports for pydym
"""

from .dynamic_decomposition import dynamic_decomposition
from .flow_data import FlowData, load
from .datum import Datum
from . import io, plotting, integrate

# Load git autogenerated version - update with setup.py update_version
from ._version import __version__

__all__ = ['io', 'plotting', 'dynamic_decomposition', 'get_modes',
           'FlowData', 'FlowDatum', 'Modes', '__version__']
